import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Aside from "@/components/aside";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['400', '500', '700'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable}antialiased`}
      >
          <div className="flex w-full overflow-x-hidden">
            <Aside />
            {children}
          </div>
      </body>
    </html>
  );
}
